cite 'about-alias'
about-alias 'common petalinux abbreviations'

# Aliases
alias sptl='source /opt/pkg/petalinux/2018.3/settings.sh'
alias pcpz='petalinux-create -t project --template zynq -n'
alias pcpsbsp='petalinux-create -t project -s'
alias plcf='petalinux-config'
alias pcgh='petalinux-config --get-hw-description'
alias pcck='petalinux-config -c kernel'
alias pccr='petalinux-config -c rootfs'
alias plbd='petalinux-build'
alias plpk='petalinux-package'
alias ppbf='petalinux-package --boot --force --fsbl ./images/linux/zynq_fsbl.elf --fpga ./images/linux/*.bit --u-boot'
alias ppfp='petalinux-package --fpga images/linux/*.bit --prebuilt'
alias pppo='petalinux-package --bsp -p'
alias plbt='petalinux-boot'
alias pbjp='petalinux-boot --jtag --prebuilt'
alias pbqp='petalinux-boot --qemu --prebuilt 3'
