cite 'about-alias'
about-alias 'systemd service'

alias sda='systemd-analyze' 
	alias sc='systemctl'
    alias scsw='systemctl show'
	alias scdr='systemctl daemon-reload'
	alias scu='systemctl --user'
	alias scus='systemctl --user start'
	alias scur='systemctl --user daemon-reload'
	alias scue='systemctl --user stop'
	alias scs='systemctl start'
	alias sce='systemctl stop'
    alias scrs='systemctl restart'
    alias scstu='systemctl status'
    alias scm='systemctl mask'
    alias scum='systemctl unmask'
    alias sck='systemctl kill'
    alias scrl='systemctl reload'
    alias scia='systemctl is-active'
    alias scea='systemctl enable'
    alias scda='systemctl disable'
    alias sclu='systemctl list-units'
    alias scluf='systemctl list-unit-files'
    alias scgd='systemctl get-default'
